//! DR-036 sub-slice `init-wrapper` ORACLE — CRITERION 1, the golden-path CHAIN
//! end-to-end: `rezidnt init --defaults <dir>` against a LIVE daemon runs
//! `doctor -> spec init -> open` and reaches a first `agent.spawned` on the fabric,
//! from a cold checkout with ZERO config edits. Needs the daemon + UDS, so it is
//! `#![cfg(unix)]` and lives in the daemon crate's tests (where `rezidnt_testkit`
//! and the sibling-binary locator are available). Modeled on
//! `spec_init_open_e2e.rs` (the sibling that solved the hard parts) and
//! `cli_verbs.rs` (the `rezidnt open`-drives-the-daemon precedent).
//!
//! ## The "init does its own open" seam problem — and the honest resolution
//! The sibling `spec_init_open_e2e.rs` opens the generated spec ITSELF over the
//! socket, so it can splice two environment-bound values into the file BETWEEN
//! generate and open: `repo = "."` -> the tempdir's absolute path, and a
//! `bin_override` stub harness the headless box can spawn. `rezidnt init` cannot be
//! driven that way: the WRAPPER does the `open` internally, in one chain, so there
//! is no seam to splice the file between its generate and open steps.
//!
//! Investigated for a daemon-honored env override that would let `init`'s OWN open
//! spawn a stub without touching the file (the module doc of `spec_init_open_e2e.rs`
//! floats a `REZIDNT_HARNESS_BIN`-style alternative). There is NONE: the spawner
//! (`crates/rezidnt-run/src/spawner.rs::for_claude_code`) resolves the harness bin
//! from the spec's `bin_override`, else the bare name `claude`; the daemon
//! (`bins/rezidentd/src/runs.rs::harness_binary_resolves`) resolves that bare name
//! on the DAEMON PROCESS's own `PATH`. So the ONLY clean seam that lets `init`'s own
//! open reach a spawn is to make the generated spec's default harness resolvable ON
//! THE DAEMON's PATH — a `claude` stub in a dir the daemon is started with. That is
//! the SAME class of environment substitution the sibling documents (the harness
//! executable the headless box lacks), applied WITHOUT mutating the generated file:
//! nothing the generator wrote is spliced away — the daemon simply finds a real
//! `claude` to run. Two environment facts make the headless box honest, and neither
//! touches the generated bytes: (1) the daemon is started with its cwd set to the
//! operator's scaffolded project dir, so the generated `repo = "."` canonicalizes to
//! THAT git repo (`runs.rs` resolves a relative `repo` against the daemon cwd) — the
//! operator runs `open` from their project dir, and this reproduces that context; and
//! (2) a `claude` stub script sits in a dir on the daemon's `PATH`, so the generated
//! default `harness = "claude-code"` (bin `claude`, no `bin_override`) resolves and
//! spawns. `init` itself runs the WHOLE chain — doctor, spec generation, AND its own
//! open — and the generated file is opened UNTOUCHED (`repo = "."` verbatim on disk).
//! This is the most honest option the work order sanctions: `init` does its own open,
//! the only environment substitution is the harness executable, and the generated §13
//! shape drives the materialization.
//!
//! ## And the split the work order also sanctions (belt and suspenders)
//! Criterion 1 also asks, where no clean seam lets `init` itself spawn, to split
//! into "init chains through to the open step (a daemon-observed materialization
//! attempt)" + the already-proven "generated spec opens->spawns". The clean seam
//! DOES exist (above), so `full_chain_reaches_agent_spawned` proves the strong form.
//! `chain_reaches_open_step_daemon_observed` additionally pins the WEAKER,
//! seam-independent half: `init` reaches the daemon's `open` — a `workspace.opened`
//! fact lands for this open's correlation — proving the chain traversed doctor +
//! spec-init and reached its own open. `workspace.opened` is published BEFORE any
//! spawn, so that half holds independently of whether a harness stub is present (no
//! premise-skip that could false-green while `init` is absent). The already-proven
//! "generated default spec, made spawnable, reaches agent.spawned" is
//! `spec_init_open_e2e.rs::generated_default_spec_opens_and_spawns` — this file does
//! not duplicate it.
//!
//! Cross-platform: `#![cfg(unix)]` (needs the daemon + UDS). Host `/vet` cannot
//! reach this; lint/run on WSL per the project's host-vs-WSL rule.

#![cfg(unix)]

mod common;

use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Child, Command};
use std::time::{Duration, Instant};

use common::{cli_bin, connect, daemon_bin, read_until, send_line};

const TAIL_DEADLINE: Duration = Duration::from_secs(20);

/// A daemon started with an EXPLICIT cwd and `PATH` (unlike testkit `start_daemon`,
/// which sets neither), plus a temp socket/db. Criterion 1 needs both: the cwd so
/// the generated `repo = "."` resolves to the operator's scaffolded project, and a
/// `PATH` the `claude` stub can sit on so the default harness spawns. Kills the
/// daemon on drop.
struct DaemonWithCwd {
    child: Child,
    socket: PathBuf,
    db: PathBuf,
    _dir: tempfile::TempDir,
}

impl Drop for DaemonWithCwd {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

/// Start `rezidentd` with `cwd` as its working directory and `path` as its `PATH`
/// (so a bare-name harness resolves against a dir the test controls). Waits for the
/// socket to appear. The socket/db live in their own temp dir, distinct from `cwd`
/// (the operator's project), so daemon state never lands in the scaffolded repo.
fn start_daemon_in(cwd: &Path, path: &str) -> DaemonWithCwd {
    let dir = tempfile::tempdir().expect("tempdir");
    let socket = dir.path().join("rezidnt.sock");
    let db = dir.path().join("events.db");
    let child = Command::new(daemon_bin())
        .current_dir(cwd)
        .env("REZIDNT_SOCKET", &socket)
        .env("REZIDNT_DB", &db)
        .env("PATH", path)
        .spawn()
        .expect("spawn rezidentd with explicit cwd/PATH");
    let deadline = Instant::now() + Duration::from_secs(5);
    while !socket.exists() {
        assert!(Instant::now() < deadline, "daemon socket never appeared");
        std::thread::sleep(Duration::from_millis(50));
    }
    DaemonWithCwd {
        child,
        socket,
        db,
        _dir: dir,
    }
}

/// Write an executable `claude` stub into `dir` (bare name — the default spec's
/// harness bin) that emits the S1 stream-json lines the adapter maps, holding the
/// run open `gap_ms` between lines. Mirrors testkit `stub_harness` but is NAMED
/// `claude` so the generated default `harness = "claude-code"` (bin `claude`)
/// resolves to it when `dir` is on the daemon's PATH.
fn claude_stub(dir: &Path, gap_ms: u64) -> PathBuf {
    let gap_s = gap_ms as f64 / 1000.0;
    let script = dir.join("claude");
    std::fs::write(
        &script,
        format!(
            r#"#!/bin/sh
echo '{{"type":"system","subtype":"init","session_id":"fixture-session","claude_code_version":"2.1.191","tools":[]}}'
sleep {gap_s}
echo '{{"type":"assistant","message":{{"role":"assistant","content":[{{"type":"text","text":"working"}}]}}}}'
sleep {gap_s}
echo '{{"type":"result","subtype":"success","is_error":false,"num_turns":1,"duration_ms":5,"total_cost_usd":0.001,"usage":{{"input_tokens":1,"output_tokens":1}},"session_id":"fixture-session"}}'
"#
        ),
    )
    .expect("write claude stub");
    let mut perms = std::fs::metadata(&script).expect("stat").permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(&script, perms).expect("chmod claude stub");
    script
}

/// `git init` a directory so the daemon can allocate a worktree in it (the
/// generated `repo = "."` canonicalizes to the daemon cwd, which is this dir).
fn git_init(dir: &Path) {
    let status = Command::new("git")
        .args(["init", "-q"])
        .current_dir(dir)
        .status()
        .expect("git init the scaffolded project dir");
    assert!(status.success(), "git init the scaffolded repo dir");
}

/// Run `rezidnt init --defaults <dir>` against `daemon`, with `PATH` (the daemon
/// must ALSO see this PATH — set on the daemon at start; the CLI's own PATH governs
/// nothing here since the daemon does the spawn). Returns (exit, stdout, stderr).
fn run_init_defaults(
    socket: &Path,
    db: &Path,
    dir: &Path,
    path: &str,
) -> (Option<i32>, String, String) {
    let out = Command::new(cli_bin())
        .arg("init")
        .arg("--defaults")
        .arg(dir.to_str().expect("utf8 dir"))
        .env("REZIDNT_SOCKET", socket)
        .env("REZIDNT_DB", db)
        .env("PATH", path)
        .output()
        .expect("spawn rezidnt init --defaults");
    (
        out.status.code(),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

/// The current process `PATH`, so the daemon/CLI keep resolving `git` and system
/// tools while we PREPEND a dir holding the `claude` stub. Returned as a `String`.
fn path_with_prepended(dir: &Path) -> String {
    let base = std::env::var_os("PATH").unwrap_or_default();
    let mut dirs = vec![dir.to_path_buf()];
    dirs.extend(std::env::split_paths(&base));
    std::env::join_paths(dirs)
        .expect("join PATH")
        .to_str()
        .expect("utf8 PATH")
        .to_string()
}

/// CRITERION 1 (the strong form — `init` does its OWN open and reaches a spawn).
/// `rezidnt init --defaults <dir>` against a live daemon runs the WHOLE chain
/// (doctor -> spec generation -> its own open) and reaches a first `agent.spawned`
/// on the fabric, with the generated `rezidnt.toml` opened UNTOUCHED. The single
/// environment substitution is the harness executable: a `claude` stub on the
/// daemon's PATH (the headless box has no real `claude`), plus the daemon started in
/// the scaffolded project dir so the generated `repo = "."` resolves there — neither
/// mutates the generated bytes (see the module doc's seam discussion). Exit 0 and
/// an observed `agent.spawned` for THIS open's correlation are the golden-path
/// "zero config edits, reaches a gated run" clause, end to end through the wrapper.
///
/// Written RED before the `init` verb existed: clap rejected `init` (exit 2, no
/// chain), so no `agent.spawned` ever landed and the exit-0 pin failed.
#[test]
fn full_chain_reaches_agent_spawned() {
    // The operator's cold checkout: a git repo the daemon opens as `repo = "."`.
    let project = tempfile::tempdir().expect("project tempdir");
    git_init(project.path());

    // The one environment substitution: a `claude` stub the daemon can spawn, on a
    // dir we PREPEND to PATH. No real `claude` exists on a headless box.
    let bindir = tempfile::tempdir().expect("bindir tempdir");
    claude_stub(bindir.path(), 4_000);
    let path = path_with_prepended(bindir.path());

    // Daemon cwd = the operator's project (so generated `repo = "."` resolves to it);
    // daemon PATH carries the `claude` stub (so the default harness spawns).
    let daemon = start_daemon_in(project.path(), &path);

    // Subscribe BEFORE init so no fact is missed, then run the whole wrapper chain.
    let mut tail = connect(&daemon.socket);
    send_line(&mut tail, r#"{"op":"tail"}"#);

    let (code, stdout, stderr) =
        run_init_defaults(&daemon.socket, &daemon.db, project.path(), &path);

    // The generated file must exist and be UNTOUCHED (repo = "." verbatim) — the
    // wrapper opened what it generated, no config edits.
    let spec_path = project.path().join("rezidnt.toml");
    let generated = std::fs::read_to_string(&spec_path).unwrap_or_else(|e| {
        panic!(
            "init --defaults must generate {} on the way to open (chain reached spec-init?): \
             {e}; exit {code:?}; stderr: {stderr}",
            spec_path.display()
        )
    });
    assert!(
        generated.contains("repo = \".\""),
        "the wrapper must open the spec it GENERATED, untouched — the generated `repo = \".\"` \
         must be verbatim on disk (zero config edits): generated:\n{generated}"
    );

    assert_eq!(
        code,
        Some(0),
        "rezidnt init --defaults must run doctor -> spec init -> its own open and SUCCEED \
         (exit 0) reaching a gated run; stdout: {stdout:?}; stderr: {stderr}"
    );

    // The fabric proof: THIS open's chain reached a first agent.spawned carrying a
    // 26-char run ULID — the golden-path "reaches a gated run" clause through init.
    let lines = read_until(&mut tail, TAIL_DEADLINE, |v| {
        v["subject"] == "agent.spawned"
    });
    let run = lines
        .iter()
        .find(|v| v["subject"] == "agent.spawned")
        .expect("agent.spawned on the fabric")["payload"]["run"]
        .as_str()
        .expect("agent.spawned carries the run ulid")
        .to_string();
    assert_eq!(
        run.len(),
        26,
        "init's own open reached a first agent.spawned with a 26-char run ULID — the golden-path \
         chain (doctor -> spec init -> open -> gated run) holds end to end: run={run:?}"
    );
}

/// CRITERION 1 (the weaker, seam-independent half — the chain REACHES the open step,
/// daemon-observed, independent of any harness-stub seam). `rezidnt init --defaults
/// <dir>` against a live daemon whose cwd is the scaffolded project: the daemon
/// canonicalizes the generated `repo = "."` and publishes `workspace.opened` for this
/// open's correlation. `workspace.opened` is emitted at step 1 of materialization —
/// BEFORE the harness is even spawned (`runs.rs`) — so it lands whether or not the
/// default `claude` harness subsequently resolves/spawns on this box. Observing it
/// proves the wrapper traversed doctor + spec-init and reached its OWN open (a
/// daemon-observed materialization attempt), WITHOUT depending on a harness stub and
/// WITHOUT pretending a spawn occurred. This is why no `claude`-present premise-skip
/// is needed: the assertion holds identically with or without a real `claude`, so it
/// can never green-pass by skipping while `init` is absent. The already-proven
/// "generated default spec, made spawnable, reaches agent.spawned" is
/// `spec_init_open_e2e.rs::generated_default_spec_opens_and_spawns`; the STRONG form
/// (init's own open reaching agent.spawned) is `full_chain_reaches_agent_spawned`.
///
/// Written RED before the `init` verb existed: clap rejected `init` (exit 2, no
/// chain), so no `rezidnt.toml` was generated and no `workspace.opened` for this
/// open's correlation ever landed — an honest red that does not skip.
#[test]
fn chain_reaches_open_step_daemon_observed() {
    let project = tempfile::tempdir().expect("project tempdir");
    git_init(project.path());

    // The inherited PATH (so `git` resolves for worktree allocation). We do NOT
    // require a `claude` stub: this test proves the chain REACHES open via
    // `workspace.opened`, which precedes any spawn — so a real `claude` being present
    // or absent does not change the assertion (no premise-skip that could false-green
    // while `init` is absent).
    let path = std::env::var("PATH").unwrap_or_default();
    let daemon = start_daemon_in(project.path(), &path);

    let mut tail = connect(&daemon.socket);
    send_line(&mut tail, r#"{"op":"tail"}"#);

    let (_code, _stdout, stderr) =
        run_init_defaults(&daemon.socket, &daemon.db, project.path(), &path);

    // The generated file must exist (chain reached spec-init) — a precondition of
    // open, and an honest-red anchor: while `init` is absent no file is written and
    // this fails, unconditionally.
    let spec_path = project.path().join("rezidnt.toml");
    assert!(
        spec_path.exists(),
        "init must generate {} before its open step (chain reached spec-init?); stderr: {stderr}",
        spec_path.display()
    );

    // The daemon-observed proof the chain REACHED open: `workspace.opened` lands (the
    // open step ran, materialization was attempted) — emitted before the spawn, so
    // this holds whether or not the default harness spawns on this box.
    let lines = read_until(&mut tail, TAIL_DEADLINE, |v| {
        v["subject"] == "workspace.opened"
    });
    assert!(
        lines.iter().any(|v| v["subject"] == "workspace.opened"),
        "the wrapper must REACH its open step — the daemon must publish `workspace.opened` \
         (a daemon-observed materialization attempt), proving init traversed doctor + \
         spec-init and reached its own open. saw: {lines:?}; stderr: {stderr}"
    );
}
